const $=id=>document.getElementById(id), canvas=$('drawing'), ctx=canvas.getContext('2d');
let tool='pen',items=[],undone=[],active=null;
const names={pen:'자유선',line:'직선',eraser:'지우개',text:'지명',coast:'해안선',route:'항로'};
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function paint(item){ctx.save();ctx.globalCompositeOperation=item.tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=item.color;ctx.fillStyle=item.color;ctx.lineWidth=item.width;ctx.lineCap='round';ctx.lineJoin='round';if(item.tool==='route')ctx.setLineDash([14,12]);if(item.tool==='text'){ctx.font=`${item.size}px Georgia, serif`;ctx.fillText(item.text,item.points[0].x,item.points[0].y)}else{ctx.beginPath();const ps=item.points;ctx.moveTo(ps[0].x,ps[0].y);if(ps.length===1){ctx.lineTo(ps[0].x+.01,ps[0].y)}else for(const p of ps.slice(1))ctx.lineTo(p.x,p.y);if(item.tool==='coast'){ctx.save();ctx.globalAlpha=.2;ctx.lineWidth=item.width+22;ctx.stroke();ctx.restore();ctx.save();ctx.strokeStyle='#e8d2a2';ctx.lineWidth=item.width+14;ctx.stroke();ctx.restore()}ctx.stroke()}ctx.restore()}
function ornament(c){if(!$('frame').checked||$('backgroundMode').value==='reference')return;c.save();c.strokeStyle='#6d4c2c';c.lineWidth=2;c.strokeRect(62,62,canvas.width-124,canvas.height-124);c.lineWidth=1;c.strokeRect(70,70,canvas.width-140,canvas.height-140);c.restore()}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);items.forEach(paint);if(active)paint(active);ornament(ctx);$('undo').disabled=!items.length;$('redo').disabled=!undone.length}
function commit(){if(active){items.push(active);active=null;undone=[];render();$('status').textContent='그림에 반영했습니다. PNG로 저장할 수 있습니다.'}}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('selected',x===b));$('textControls').hidden=tool!=='text';$('toolLabel').textContent=names[tool]+' 도구';$('status').textContent=tool==='text'?'지명을 입력하고 지도에서 위치를 누르세요.':'양피지 위에 드래그해서 그리세요.'});
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{$('color').value=b.dataset.color});$('width').oninput=()=>{$('widthValue').value=$('width').value};
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||active)return;e.preventDefault();const p=point(e);if(tool==='text'&&!$('place').value.trim()){$('place').focus();$('status').textContent='먼저 지명을 입력해 주세요.';return}active={tool,color:$('color').value,width:Number($('width').value)*2,size:Number($('fontSize').value)*2,text:$('place').value.trim(),points:[p]};if(tool==='text'){commit();return}canvas.setPointerCapture(e.pointerId);render()});
canvas.addEventListener('pointermove',e=>{if(!active)return;const p=point(e);if(active.tool==='line')active.points=[active.points[0],p];else active.points.push(p);render()});canvas.addEventListener('pointerup',commit);canvas.addEventListener('pointercancel',()=>{active=null;render()});canvas.addEventListener('lostpointercapture',commit);
function undo(){if(active)return;if(items.length)undone.push(items.pop());render()}function redo(){if(active)return;if(undone.length)items.push(undone.pop());render()}$('undo').onclick=undo;$('redo').onclick=redo;
$('clear').onclick=()=>{if(active||!items.length)return;if(confirm('지금 그린 내용을 모두 지울까요? PNG로 저장하지 않은 그림은 사라집니다.')){items=[];undone=[];render();$('status').textContent='새 지도를 그릴 준비가 되었습니다.'}};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}});
$('export').onclick=async()=>{if(active)commit();const bg=$('background');try{await bg.decode();const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const c=out.getContext('2d');if($('backgroundMode').value==='blank'){c.save();c.translate(out.width,0);c.rotate(Math.PI/2);c.drawImage(bg,0,0,out.height,out.width);c.restore()}else c.drawImage(bg,0,0,out.width,out.height);c.drawImage(canvas,0,0);out.toBlob(blob=>{if(!blob){$('status').textContent='저장에 실패했습니다. 다시 시도해 주세요.';return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='my-parchment-map.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('status').textContent='지도를 PNG로 저장했습니다.'},'image/png')}catch{$('status').textContent='배경 이미지를 불러오지 못했습니다. 새로고침 후 다시 시도해 주세요.'}};
window.addEventListener('beforeunload',e=>{if(items.length){e.preventDefault();e.returnValue=''}});render();

$('frame').onchange=render;
$('backgroundMode').onchange=()=>{const ref=$('backgroundMode').value==='reference';$('background').src=ref?'assets/reference-map.png':'assets/parchment.png';$('background').alt=ref?'참고용 해적 지도':'빈 양피지 지도 배경';document.querySelector('.paper').classList.toggle('reference',ref);$('status').textContent=ref?'참고 지도 위에 항로와 지명을 더해 보세요.':'빈 양피지에 나만의 세계를 그려 보세요.';render()};
